config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  root "todo_lists#index"
  resources :todo_lists  do
    resources :todo_items do
      member do
        patch :complete
        patch :reopen
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items,  :dependent => :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todo_lists
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      sessions[:user_id] = @user.id
      redirect_to '/welcome'
    else
      redirect_to '/login'
    end
  end

  def login
  end

  def welcome
  end

  def page_requires_login
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def update
    @todo_item.update_attribute(:content, params[:content])
    redirect_to @todo_list, notice: "Todo item was updated."
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      redirect_to @todo_list, notice: "Todo item was deleted."
    else
      redirect_to @todo_list, notice: "Todo item could not be deleted."
    end
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: "Todo item was marked as completed."
  end

  def reopen
    @todo_item.update_attribute(:completed_at, nil)
    redirect_to @todo_list, notice: "Todo item was reopened."
  end

  private
  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all.order('created_at ASC')
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username, :password))
    session[:user_id] = @user.id
    redirect_to '/welcome'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todo app RoR
    = stylesheet_link_tag 'bundle_application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap", :rel => "stylesheet"}
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}
  %body
    .container.app
      - flash.each do |type, msg|
        .alert.alert-info.mb-3.js-alert= msg
      = yield

app/views/todo_items/_form.html.haml
.form
  = form_for([@todo_list, @todo_list.todo_items.build]) do |f|
    .form-group.d-flex
      = f.text_field :content, placeholder: "New Todo", class: "form-control mr-2", required: true
      = f.submit class: 'btn btn-primary', value: 'Add todo'

app/views/todo_items/_todo_item.html.haml
.d-flex.mb-2
  .d-flex.align-items-center.mr-4
    - if todo_item.completed?
      %i.fa.fa-check{:style => "opacity: 0.4;"}
    - else
      = link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do
        %i.fa.fa-circle-thin{ 'data-toggle': "tooltip", 'data-placement': "top", title: "Mark as completed" }

  .flex-grow-1.js-item-content{ 'data-todo-item-id': todo_item.id }
    .d-flex.align-items-center.h-100
      - if todo_item.completed?
        %div{:style => "opacity: 0.4;"}
          %strike.js-item-content-text= todo_item.content
      - else
        %div.js-item-content-text= todo_item.content

  .todo-item-edit.js-todo-item-edit.flex-grow-1{ 'data-todo-item-id': todo_item.id }
    =form_with(url: todo_list_todo_item_path(@todo_list, todo_item.id ), method: "PATCH") do |f|
      .d-flex.mr-4
        = f.text_field :content, placeholder: "Edit todo content", class: "form-control mr-2", value: todo_item.content, required: true
        = f.submit content: 'Edit todo', class: 'btn btn-primary'

  - if todo_item.completed?
    .d-flex.align-items-center.mr-4
      = link_to reopen_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch, class: 'text-primary', 'data-toggle': "tooltip", 'data-placement': "top", title: "Reopen task" do
        %i.fa.fa-reply
  %button.btn.btn-outline-secondary.mr-4.js-todo-item-edit-btn{ 'data-todo-item-id': todo_item.id, 'data-active-text': 'Cancel', 'data-unactive-text': 'Edit', 'data-is-active': false }
    Edit

  .d-flex.align-items-center
    = link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'text-secondary' do
      %i.fa.fa-trash

app/views/todo_lists/_back_link.html.haml
- link ||= nil

.mb-2
  = link_to link, class: "back-link" do
    %i.fa.fa-chevron-left.mr-1
    Back

app/views/todo_lists/_form.html.haml
= form_with(model: todo_list, local: true) do |form|
  - if todo_list.errors.any?
    #error_explanation
      %h2
        = pluralize(todo_list.errors.count, "error")
        prohibited this todo_list from being saved:
      %ul
        - todo_list.errors.full_messages.each do |message|
          %li= message
  .form-group
    %label{'data-toggle': "tooltip", 'data-placement': "top", title: "Required field"}
      Title
      %span.text-danger *
    = form.text_field :title, class: 'form-control', required: true
  .form-group
    = form.label :description
    = form.text_area :description, class: 'form-control', rows: 5
  .actions.mt-4
    = form.submit class: "btn btn-primary mr-2"

app/views/todo_lists/edit.html.haml
= render partial: 'back_link', locals: { link: @todo_list }
.card
  .card-body
    %h2.todo_list_title Edit Todo List
    .form
      = render 'form', todo_list: @todo_list

app/views/todo_lists/index.html.haml
%div
  .container
    .d-flex.justify-content-between.align-items-center.mb-4
      %h1.text-center To do Lists
      = link_to "New Todo List", new_todo_list_path, class: 'btn btn-primary'
  %div
    - @todo_lists.each do |todo_list|
      .lists__item
        = link_to todo_list, class: 'card lists__item-card' do
          .card-body
            %h4.card-title= todo_list.title
            %p.todo_list_sub_title= todo_list.description

app/views/todo_lists/new.html.haml
= render partial: 'back_link', locals: { link: todo_lists_path }
.card
  .card-body
    %h2.todo_list_title New Todo List
    .form
      = render 'form', todo_list: @todo_list

app/views/todo_lists/show.html.haml
.mb-2
  = link_to todo_lists_path, class: "back-link" do
    %i.fa.fa-chevron-left.mr-1
    %span Back
.card
  .card-body
    .mb-4
      .d-flex.justify-content-between.align-items-center.mb-2
        %h2= @todo_list.title
        .d-flex
          = link_to 'Edit', edit_todo_list_path(@todo_list), class: "btn btn-outline-secondary mr-2"
          = link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger mr-2"
      %p= @todo_list.description
    .mb-4
      = render @todo_list.todo_items
    = render "todo_items/form"

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/users/new.html.haml
%h1 Sign Up
= form_for @user do |f|
  = f.label :username
  %br
  = f.text_field :username
  %br
  = f.label :password
  %br
  = f.password_field :password
  %br
  = f.submit